import { db } from "./firebase-config.js";
import { collection, onSnapshot, query, orderBy } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const $=id=>document.getElementById(id);
let products=[],favorites=JSON.parse(localStorage.getItem("ibratFavorites")||"[]"),cart=JSON.parse(localStorage.getItem("ibratCart")||"[]"),gallery=[],galleryIndex=0;
$("menuButton")?.addEventListener("click",()=>$("mainNav").classList.toggle("open"));$("mainNav")?.querySelectorAll("a").forEach(a=>a.onclick=()=>$("mainNav").classList.remove("open"));
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function img(n=""){const c=String(n).replace(/^images\//,"");return c?`./images/${encodeURIComponent(c).replaceAll("%2F","/")}`:"./logo.png"}
function imgs(p={}){if(Array.isArray(p.images)&&p.images.length)return p.images;if(p.imageName)return[p.imageName];return[]}
function main(p){const a=imgs(p);return a.length?img(a[0]):(p.image||"./logo.png")}
function active(){return products.filter(p=>p.status!=="hidden").sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||Number(a.sortOrder||0)-Number(b.sortOrder||0)||(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))}
function sync(){const v=new Set(products.map(p=>p.id));favorites=favorites.filter(v.has,v);cart=cart.filter(v.has,v);localStorage.setItem("ibratFavorites",JSON.stringify(favorites));localStorage.setItem("ibratCart",JSON.stringify(cart));$("favoritesCount").textContent=favorites.length;$("cartCount").textContent=cart.length}
function categories(){const s=$("catalogCategory").value,c=[...new Set(active().map(p=>p.category).filter(Boolean))].sort();$("catalogCategory").innerHTML='<option value="">Barcha kategoriyalar</option>'+c.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");if(c.includes(s))$("catalogCategory").value=s}
function card(p){const sold=p.soldOut||Number(p.stock)===0,f=favorites.includes(p.id),a=imgs(p);return`<article class="product-card ${sold?"sold-card":""}"><div class="product-image-wrap"><img loading="lazy" src="${esc(main(p))}" alt="${esc(p.name)}">${p.featured?'<span class="featured-badge">TOP</span>':""}${p.isNew?'<span class="new-badge">YANGI</span>':""}${sold?'<span class="sold-badge">SOTILDI</span>':""}<button class="heart-button ${f?"active":""}" data-favorite="${p.id}" type="button">♥</button>${a.length>1?`<span class="image-count">📷 ${a.length}</span>`:""}</div><div class="product-body"><span class="category-badge">${esc(p.category||"Boshqa")}</span><h3>${esc(p.name)}</h3><p>${esc(p.description||"Qo‘shimcha ma’lumot uchun bog‘laning.")}</p><div class="price-row"><strong>${esc(p.price)}</strong>${p.oldPrice?`<del>${esc(p.oldPrice)}</del>`:""}</div><div class="stock-line">${sold?"Hozir sotuvda yo‘q":`Omborda: ${Number(p.stock??1)} ta`}</div><div class="product-actions"><button class="button button-dark" data-detail="${p.id}" type="button">Batafsil</button><button class="button button-gold" data-cart="${p.id}" type="button" ${sold?"disabled":""}>Savatchaga</button></div></div></article>`}
function render(){const q=$("catalogSearch").value.trim().toLowerCase(),c=$("catalogCategory").value,l=active().filter(p=>(!q||`${p.name} ${p.category} ${p.description} ${p.price}`.toLowerCase().includes(q))&&(!c||p.category===c));$("catalogCount").textContent=`${l.length} ta mahsulot`;$("catalogGrid").innerHTML=l.length?l.map(card).join(""):'<div class="empty-state">Hozircha mos mahsulot topilmadi.</div>'}
function featured(){const l=active().filter(p=>p.featured).slice(0,10);$("featuredSlider").innerHTML=l.length?l.map(card).join(""):'<div class="empty-state">Top mahsulotlar hali belgilanmagan.</div>'}
function galleryRender(i=0){galleryIndex=(i+gallery.length)%gallery.length;const m=$("modalMainImage");if(m)m.src=img(gallery[galleryIndex]);document.querySelectorAll(".gallery-thumb").forEach((t,k)=>t.classList.toggle("active",k===galleryIndex))}
function detail(p){gallery=imgs(p);if(!gallery.length)gallery=[""];$("productModalContent").innerHTML=`<div class="modal-product-grid"><div class="product-gallery"><img id="modalMainImage" class="modal-main-image" src="${esc(img(gallery[0]))}" alt="${esc(p.name)}"><div class="gallery-thumbs">${gallery.map((n,i)=>`<button class="gallery-thumb ${i===0?"active":""}" data-gallery-index="${i}" type="button"><img src="${esc(img(n))}" alt=""></button>`).join("")}</div></div><div><span class="category-badge">${esc(p.category||"Boshqa")}</span>${p.isNew?'<span class="inline-new-badge">YANGI</span>':""}<h2>${esc(p.name)}</h2><p>${esc(p.description||"")}</p><div class="price-row modal-price"><strong>${esc(p.price)}</strong>${p.oldPrice?`<del>${esc(p.oldPrice)}</del>`:""}</div><p><b>Holati:</b> ${p.soldOut||Number(p.stock)===0?"Sotuvda yo‘q":`Omborda ${Number(p.stock??1)} ta`}</p><div class="button-row">${p.video?`<a class="button button-dark" target="_blank" rel="noopener" href="${esc(p.video)}">Videoni ko‘rish</a>`:""}<a class="button button-gold" target="_blank" rel="noopener" href="https://t.me/ibratmebel8909?text=${encodeURIComponent(`Assalomu alaykum. ${p.name} mahsulotiga buyurtma bermoqchiman.`)}">Buyurtma berish</a></div></div></div>`;$("productModal").showModal()}
$("productModalContent").onclick=e=>{const t=e.target.closest("[data-gallery-index]");if(t)galleryRender(Number(t.dataset.galleryIndex))};$("lightboxPrev").onclick=()=>galleryRender(galleryIndex-1);$("lightboxNext").onclick=()=>galleryRender(galleryIndex+1);
function list(type){const ids=type==="favorites"?favorites:cart,l=ids.map(id=>products.find(p=>p.id===id)).filter(Boolean);$("listModalContent").innerHTML=`<h2>${type==="favorites"?"Sevimli mahsulotlar":"Savatcha"}</h2>`+(l.length?l.map(p=>`<div class="list-product"><img src="${esc(main(p))}" alt=""><div><b>${esc(p.name)}</b><span>${esc(p.price)}</span></div><button data-remove-list="${type}" data-id="${p.id}" type="button">Olib tashlash</button></div>`).join(""):"<p>Hozircha bo‘sh.</p>");$("cartCheckoutButton").hidden=type!=="cart"||!l.length;$("listModal").showModal()}
document.addEventListener("click",e=>{const f=e.target.closest("[data-favorite]"),a=e.target.closest("[data-cart]"),d=e.target.closest("[data-detail]");if(f){const id=f.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];sync();render();featured()}if(a){const id=a.dataset.cart;if(!cart.includes(id))cart.push(id);sync();a.textContent="Qo‘shildi ✓"}if(d){const p=products.find(x=>x.id===d.dataset.detail);if(p)detail(p)}})
$("favoritesButton").onclick=()=>list("favorites");$("cartButton").onclick=()=>list("cart");$("modalClose").onclick=()=>$("productModal").close();$("listModalClose").onclick=()=>$("listModal").close();
$("listModalContent").onclick=e=>{const b=e.target.closest("[data-remove-list]");if(!b)return;if(b.dataset.removeList==="favorites")favorites=favorites.filter(x=>x!==b.dataset.id);else cart=cart.filter(x=>x!==b.dataset.id);sync();list(b.dataset.removeList);render();featured()};
$("cartCheckoutButton").onclick=()=>{const l=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);if(!l.length)return;window.open(`https://t.me/ibratmebel8909?text=${encodeURIComponent("Assalomu alaykum! Quyidagi mahsulotlarga buyurtma bermoqchiman:\n\n"+l.map((p,i)=>`${i+1}. ${p.name} — ${p.price}`).join("\n"))}`,"_blank","noopener")};
$("catalogSearch").oninput=render;$("catalogCategory").onchange=render;
onSnapshot(query(collection(db,"products"),orderBy("createdAt","desc")),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));categories();sync();render();featured()},e=>{console.error(e);$("catalogGrid").innerHTML='<div class="empty-state">Mahsulotlarni yuklashda xatolik.</div>'});
$("buyurtma").onsubmit=e=>{e.preventDefault();const t=encodeURIComponent(`Assalomu alaykum!\nIsm: ${$("customerName").value.trim()}\nTelefon: ${$("customerPhone").value.trim()}\nXizmat: ${$("customerService").value}\nIzoh: ${$("customerMessage").value.trim()}`);window.open(`https://t.me/ibratmebel8909?text=${t}`,"_blank","noopener")};
