import { auth, db } from "./firebase-config.js";
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";

const $=id=>document.getElementById(id);
let customers=[],inventory=[],production=[],finance=[];
let financeChart=null,productionChart=null;

const labels={new:"Yangi",design:"Dizayn",cutting:"Kesish",edge:"Kromka",assembly:"Yig‘ish",ready:"Tayyor",delivered:"Yetkazildi"};
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function money(n){return Number(n||0).toLocaleString("uz-UZ")+" so‘m"}
function toast(m){const t=$("erpToast");t.textContent=m;t.classList.add("show");clearTimeout(t._);t._=setTimeout(()=>t.classList.remove("show"),2500)}
function todayStart(){const d=new Date();d.setHours(0,0,0,0);return d}

$("erpLoginForm").onsubmit=async e=>{e.preventDefault();$("erpLoginMessage").textContent="Tekshirilmoqda...";try{await signInWithEmailAndPassword(auth,$("erpEmail").value.trim(),$("erpPassword").value);$("erpLoginMessage").textContent=""}catch(err){console.error(err);$("erpLoginMessage").textContent="Email yoki parol noto‘g‘ri."}};
$("erpLogout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{$("erpLogin").hidden=!!u;$("erpApp").hidden=!u;$("erpUser").textContent=u?u.email:""});

document.querySelectorAll("[data-erp-tab]").forEach(b=>b.onclick=()=>{
  document.querySelectorAll("[data-erp-tab]").forEach(x=>x.classList.remove("active"));
  b.classList.add("active");document.querySelectorAll(".erp-view").forEach(v=>v.classList.remove("active"));
  $(`erpView${b.dataset.erpTab[0].toUpperCase()+b.dataset.erpTab.slice(1)}`).classList.add("active");
  if(b.dataset.erpTab==="dashboard")setTimeout(renderCharts,40);
});

function updateKpis(){
  $("kpiCustomers").textContent=customers.length;$("kpiInventory").textContent=inventory.length;
  $("kpiProduction").textContent=production.filter(p=>!["ready","delivered"].includes(p.status)).length;
  const start=todayStart();const todays=finance.filter(f=>f.createdAt?.toDate?.()>=start);
  const income=todays.filter(f=>f.type==="income").reduce((s,f)=>s+Number(f.amount||0),0);
  const expense=todays.filter(f=>f.type==="expense").reduce((s,f)=>s+Number(f.amount||0),0);
  $("kpiIncome").textContent=money(income);$("kpiExpense").textContent=money(expense);$("kpiProfit").textContent=money(income-expense);
}
function populateCustomers(){
  $("prodCustomer").innerHTML='<option value="">Mijoz tanlang</option>'+customers.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone)}</option>`).join("");
}
function clearCustomer(){["customerId","crmName","crmPhone","crmAddress","crmNote"].forEach(id=>$(id).value="");$("crmDebt").value=0;$("cancelCustomerEdit").hidden=true}
$("customerForm").onsubmit=async e=>{e.preventDefault();const data={name:$("crmName").value.trim(),phone:$("crmPhone").value.trim(),address:$("crmAddress").value.trim(),debt:Number($("crmDebt").value||0),note:$("crmNote").value.trim(),updatedAt:serverTimestamp()};const id=$("customerId").value;if(id)await updateDoc(doc(db,"customers",id),data);else await addDoc(collection(db,"customers"),{...data,createdAt:serverTimestamp()});clearCustomer();toast("Mijoz saqlandi")};$("cancelCustomerEdit").onclick=clearCustomer;
function renderCustomers(){const q=$("customerSearch").value.toLowerCase();const l=customers.filter(c=>!q||`${c.name} ${c.phone} ${c.address}`.toLowerCase().includes(q));$("customersList").innerHTML=l.length?l.map(c=>`<div class="erp-row"><div><h3>${esc(c.name)}</h3><p>${esc(c.phone)} · ${esc(c.address||"Manzil yo‘q")}</p>${Number(c.debt)>0?`<span class="status-pill debt-pill">Qarz: ${money(c.debt)}</span>`:""}</div><div class="erp-row-actions"><button class="edit-action" data-edit-customer="${c.id}">Tahrir</button><button class="delete-action" data-delete-customer="${c.id}">O‘chirish</button></div></div>`).join(""):"<p>Mijozlar yo‘q.</p>"}
$("customerSearch").oninput=renderCustomers;$("customersList").onclick=async e=>{const ed=e.target.closest("[data-edit-customer]"),del=e.target.closest("[data-delete-customer]");if(ed){const c=customers.find(x=>x.id===ed.dataset.editCustomer);$("customerId").value=c.id;$("crmName").value=c.name||"";$("crmPhone").value=c.phone||"";$("crmAddress").value=c.address||"";$("crmDebt").value=c.debt||0;$("crmNote").value=c.note||"";$("cancelCustomerEdit").hidden=false}if(del&&confirm("Mijoz o‘chirilsinmi?"))await deleteDoc(doc(db,"customers",del.dataset.deleteCustomer))};

function clearInventory(){["inventoryId","invName"].forEach(id=>$(id).value="");$("invQuantity").value="";$("invMin").value=5;$("invCost").value=0;$("cancelInventoryEdit").hidden=true}
$("inventoryForm").onsubmit=async e=>{e.preventDefault();const data={name:$("invName").value.trim(),category:$("invCategory").value,quantity:Number($("invQuantity").value||0),unit:$("invUnit").value,minQuantity:Number($("invMin").value||0),cost:Number($("invCost").value||0),updatedAt:serverTimestamp()};const id=$("inventoryId").value;if(id)await updateDoc(doc(db,"inventory",id),data);else await addDoc(collection(db,"inventory"),{...data,createdAt:serverTimestamp()});clearInventory();toast("Ombor yangilandi")};$("cancelInventoryEdit").onclick=clearInventory;
function renderInventory(){const q=$("inventorySearch").value.toLowerCase();const l=inventory.filter(i=>!q||`${i.name} ${i.category}`.toLowerCase().includes(q));$("inventoryList").innerHTML=l.length?l.map(i=>`<div class="erp-row"><div><h3>${esc(i.name)}</h3><p>${esc(i.category)} · ${i.quantity} ${esc(i.unit)}</p><span class="status-pill ${Number(i.quantity)<=Number(i.minQuantity)?"low-stock":""}">${Number(i.quantity)<=Number(i.minQuantity)?"Kam qoldi":"Yetarli"}</span></div><div class="erp-row-actions"><button class="edit-action" data-edit-inventory="${i.id}">Tahrir</button><button class="delete-action" data-delete-inventory="${i.id}">O‘chirish</button></div></div>`).join(""):"<p>Ombor bo‘sh.</p>";$("lowStockList").innerHTML=inventory.filter(i=>Number(i.quantity)<=Number(i.minQuantity)).slice(0,8).map(i=>`<div class="erp-row"><div><h3>${esc(i.name)}</h3><p>${i.quantity} ${esc(i.unit)}</p></div><span class="status-pill low-stock">Kam</span></div>`).join("")||"<p>Kam qolgan material yo‘q.</p>"}
$("inventorySearch").oninput=renderInventory;$("inventoryList").onclick=async e=>{const ed=e.target.closest("[data-edit-inventory]"),del=e.target.closest("[data-delete-inventory]");if(ed){const i=inventory.find(x=>x.id===ed.dataset.editInventory);$("inventoryId").value=i.id;$("invName").value=i.name||"";$("invCategory").value=i.category||"Boshqa";$("invQuantity").value=i.quantity||0;$("invUnit").value=i.unit||"dona";$("invMin").value=i.minQuantity||0;$("invCost").value=i.cost||0;$("cancelInventoryEdit").hidden=false}if(del&&confirm("Ombor mahsuloti o‘chirilsinmi?"))await deleteDoc(doc(db,"inventory",del.dataset.deleteInventory))};

function clearProduction(){["productionId","prodTitle","prodWorker","prodDeadline","prodNote"].forEach(id=>$(id).value="");$("prodCustomer").value="";$("prodStatus").value="new";$("cancelProductionEdit").hidden=true}
$("productionForm").onsubmit=async e=>{e.preventDefault();const customer=customers.find(c=>c.id===$("prodCustomer").value);const data={title:$("prodTitle").value.trim(),customerId:$("prodCustomer").value,customerName:customer?.name||"",worker:$("prodWorker").value.trim(),status:$("prodStatus").value,deadline:$("prodDeadline").value,note:$("prodNote").value.trim(),updatedAt:serverTimestamp()};const id=$("productionId").value;if(id)await updateDoc(doc(db,"production",id),data);else await addDoc(collection(db,"production"),{...data,createdAt:serverTimestamp()});clearProduction();toast("Ish vazifasi saqlandi")};$("cancelProductionEdit").onclick=clearProduction;
function renderProduction(){const f=$("productionFilter").value;const l=production.filter(p=>!f||p.status===f);const html=l.length?l.map(p=>`<div class="erp-row"><div><h3>${esc(p.title)}</h3><p>${esc(p.customerName||"Mijoz yo‘q")} · ${esc(p.worker||"Usta belgilanmagan")}</p><span class="status-pill">${labels[p.status]||p.status}</span>${p.deadline?` <span class="status-pill">${esc(p.deadline)}</span>`:""}</div><div class="erp-row-actions"><button class="edit-action" data-edit-production="${p.id}">Tahrir</button><button class="delete-action" data-delete-production="${p.id}">O‘chirish</button></div></div>`).join(""):"<p>Vazifalar yo‘q.</p>";$("productionList").innerHTML=html;$("recentProduction").innerHTML=production.slice(0,7).map(p=>`<div class="erp-row"><div><h3>${esc(p.title)}</h3><p>${esc(p.customerName||"")}</p></div><span class="status-pill">${labels[p.status]||p.status}</span></div>`).join("")||"<p>Vazifalar yo‘q.</p>"}
$("productionFilter").onchange=renderProduction;$("productionList").onclick=async e=>{const ed=e.target.closest("[data-edit-production]"),del=e.target.closest("[data-delete-production]");if(ed){const p=production.find(x=>x.id===ed.dataset.editProduction);$("productionId").value=p.id;$("prodTitle").value=p.title||"";$("prodCustomer").value=p.customerId||"";$("prodWorker").value=p.worker||"";$("prodStatus").value=p.status||"new";$("prodDeadline").value=p.deadline||"";$("prodNote").value=p.note||"";$("cancelProductionEdit").hidden=false}if(del&&confirm("Vazifa o‘chirilsinmi?"))await deleteDoc(doc(db,"production",del.dataset.deleteProduction))};

$("financeForm").onsubmit=async e=>{e.preventDefault();await addDoc(collection(db,"finance"),{type:$("finType").value,amount:Number($("finAmount").value||0),category:$("finCategory").value.trim(),note:$("finNote").value.trim(),createdAt:serverTimestamp()});$("financeForm").reset();toast("Moliya operatsiyasi saqlandi")};
function renderFinance(){const q=$("financeSearch").value.toLowerCase();const l=finance.filter(f=>!q||`${f.category} ${f.note} ${f.type}`.toLowerCase().includes(q));$("financeList").innerHTML=l.length?l.map(f=>`<div class="erp-row"><div><h3>${esc(f.category||"Operatsiya")}</h3><p>${esc(f.note||"")}</p></div><div><strong style="color:${f.type==="income"?"#087943":"#c0392b"}">${f.type==="income"?"+":"-"} ${money(f.amount)}</strong><div class="erp-row-actions"><button class="delete-action" data-delete-finance="${f.id}">O‘chirish</button></div></div></div>`).join(""):"<p>Operatsiyalar yo‘q.</p>"}
$("financeSearch").oninput=renderFinance;$("financeList").onclick=async e=>{const del=e.target.closest("[data-delete-finance]");if(del&&confirm("Operatsiya o‘chirilsinmi?"))await deleteDoc(doc(db,"finance",del.dataset.deleteFinance))};

function renderCharts(){if(!window.Chart)return;const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));d.setHours(0,0,0,0);return d});const income=[],expense=[];days.forEach(d=>{const next=new Date(d);next.setDate(next.getDate()+1);const l=finance.filter(f=>{const x=f.createdAt?.toDate?.();return x>=d&&x<next});income.push(l.filter(f=>f.type==="income").reduce((s,f)=>s+Number(f.amount||0),0));expense.push(l.filter(f=>f.type==="expense").reduce((s,f)=>s+Number(f.amount||0),0))});financeChart?.destroy();financeChart=new Chart($("financeChart"),{type:"bar",data:{labels:days.map(d=>d.toLocaleDateString("uz-UZ",{weekday:"short"})),datasets:[{label:"Kirim",data:income},{label:"Chiqim",data:expense}]},options:{responsive:true}});const counts={};production.forEach(p=>counts[labels[p.status]||p.status]=(counts[labels[p.status]||p.status]||0)+1);productionChart?.destroy();productionChart=new Chart($("productionChart"),{type:"doughnut",data:{labels:Object.keys(counts),datasets:[{data:Object.values(counts)}]},options:{responsive:true}})}

onSnapshot(query(collection(db,"customers"),orderBy("createdAt","desc")),s=>{customers=s.docs.map(d=>({id:d.id,...d.data()}));renderCustomers();populateCustomers();updateKpis()},console.error);
onSnapshot(query(collection(db,"inventory"),orderBy("createdAt","desc")),s=>{inventory=s.docs.map(d=>({id:d.id,...d.data()}));renderInventory();updateKpis()},console.error);
onSnapshot(query(collection(db,"production"),orderBy("createdAt","desc")),s=>{production=s.docs.map(d=>({id:d.id,...d.data()}));renderProduction();updateKpis();renderCharts()},console.error);
onSnapshot(query(collection(db,"finance"),orderBy("createdAt","desc")),s=>{finance=s.docs.map(d=>({id:d.id,...d.data()}));renderFinance();updateKpis();renderCharts()},console.error);
