import {loadDB,saveDB,today,money} from "./local-db.js";
const $=id=>document.getElementById(id);
let db=loadDB();
if(sessionStorage.getItem("v13PinVerified")!=="1"){sessionStorage.setItem("v23AfterLogin","1");location.href="./super-admin.html"}
const titles={home:"Boshqaruv markazi",system:"Tizim tekshiruvi",backup:"Backup markazi",guide:"Tezkor qo‘llanma"};
const num=v=>Number(v||0),esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(t._);t._=setTimeout(()=>t.classList.remove("show"),2200)}
function go(page){document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));document.querySelectorAll(".v23-page").forEach(x=>x.classList.remove("active"));$("page"+page[0].toUpperCase()+page.slice(1)).classList.add("active");$("pageTitle").textContent=titles[page];$("sidebar").classList.remove("open");if(page==="system")runChecks()}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");$("themeBtn").onclick=()=>document.documentElement.classList.toggle("dark");$("logoutBtn").onclick=()=>{sessionStorage.removeItem("v13PinVerified");location.href="./super-admin.html"};setInterval(()=>$("clock").textContent=new Date().toLocaleString("uz-UZ"),1000);
function renderHome(){db=loadDB();$("statLaminates").textContent=db.laminates.length;$("statLamStock").textContent=db.laminates.reduce((s,x)=>s+num(x.stock),0).toLocaleString("uz-UZ")+" list";$("statEdges").textContent=db.edges.length;$("statEdgeStock").textContent=db.edges.reduce((s,x)=>s+num(x.stock),0).toLocaleString("uz-UZ")+" m";const active=db.orders.filter(x=>!["Yetkazildi","Bekor qilindi"].includes(x.status));$("statOrders").textContent=active.length;$("statDebt").textContent=money(db.orders.reduce((s,x)=>s+num(x.debt),0))+" qarz";const ts=db.orders.filter(x=>x.date===today());$("statSales").textContent=money(ts.reduce((s,x)=>s+num(x.total),0));$("statSalesCount").textContent=ts.length+" ta";const low=[...db.laminates.map(x=>({...x,unit:"list"})),...db.edges.map(x=>({...x,unit:"m"}))].filter(x=>num(x.stock)<=num(x.minStock||0));$("statLow").textContent=low.length;$("lowList").innerHTML=low.slice(0,8).map(x=>`<div class="list-row"><div><strong>${esc(x.code||"")} ${esc(x.name)}</strong><p>${esc(x.location||"Joy ko‘rsatilmagan")}</p></div><span class="badge low">${x.stock} ${x.unit}</span></div>`).join("")||"<p>Kam qolgan mahsulot yo‘q.</p>";$("recentOrders").innerHTML=db.orders.slice(0,8).map(x=>`<div class="list-row"><div><strong>${esc(x.number||"")} — ${esc(x.customer||"Mijoz")}</strong><p>${esc(x.status||"")} · ${x.date||""}</p></div><span class="badge">${money(x.total)}</span></div>`).join("")||"<p>Buyurtma yo‘q.</p>"}
function runChecks(){db=loadDB();const checks=[["Mahalliy baza",!!localStorage.getItem("ibratMebelDB_v13"),"Ma’lumotlar brauzerda saqlanmoqda."],["Laminat bazasi",Array.isArray(db.laminates),`${db.laminates.length} ta mahsulot`],["Kromka bazasi",Array.isArray(db.edges),`${db.edges.length} ta mahsulot`],["Buyurtmalar",Array.isArray(db.orders),`${db.orders.length} ta buyurtma`],["Moliya",Array.isArray(db.finance),`${db.finance.length} ta yozuv`],["Smart Cut loyihalari",Array.isArray(db.cutProjects),"Smart Cut saqlash tayyor"],["Backup imkoniyati",true,"JSON eksport va import ishlaydi"],["PIN seansi",sessionStorage.getItem("v13PinVerified")==="1","Admin seansi faol"]];$("systemChecks").innerHTML=checks.map(([name,ok,info])=>`<article class="check-item ${ok?"ok":"warn"}"><strong>${ok?"✓":"!"} ${esc(name)}</strong><p>${esc(info)}</p></article>`).join("")}
$("runCheck").onclick=runChecks;
$("downloadBackup").onclick=()=>{db=loadDB();const blob=new Blob([JSON.stringify({version:"V23",exportedAt:new Date().toISOString(),data:db},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`ibrat-mebel-v23-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast("Backup yuklandi")};
$("restoreBackup").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text()),data=parsed.data||parsed;if(!data||!Array.isArray(data.laminates)||!Array.isArray(data.edges))throw new Error();if(!confirm("Backup ma’lumotlari hozirgi bazani almashtirsinmi?"))return;saveDB(data);db=loadDB();renderHome();toast("Backup tiklandi")}catch{toast("Backup fayli noto‘g‘ri")}};
window.addEventListener("storage",renderHome);window.addEventListener("ibrat-db-change",renderHome);renderHome();